export const INIT_RESTAURANT = 'INIT_RESTAURANT';
export const INIT_COMMENTS = 'INIT_COMMENTS';
export const CONFIRM_COMMENTS = 'CONFIRM_COMMENTS';
export const DECLINE_COMMENTS = 'DECLINE_COMMENTS';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
